config/routes.rb
Rails.application.routes.draw do
  get 'pages/hello'

  resources :elements

  resources :listes

end

app/models/element.rb
class Element < ActiveRecord::Base
	belongs_to :liste
end

app/models/liste.rb
class Liste < ActiveRecord::Base
	has_many :elements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: 'Element was successfully created.' }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to @element, notice: 'Element was successfully updated.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to elements_url, notice: 'Element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:name, :id_liste)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
end

app/controllers/listes_controller.rb
class ListesController < ApplicationController
  before_action :set_liste, only: [:show, :edit, :update, :destroy]

  # GET /listes
  # GET /listes.json
  def index
    @listes = Liste.all
  end

  # GET /listes/1
  # GET /listes/1.json
  def show
  end

  # GET /listes/new
  def new
    @liste = Liste.new
  end

  # GET /listes/1/edit
  def edit
  end

  # POST /listes
  # POST /listes.json
  def create
    @liste = Liste.new(liste_params)

    respond_to do |format|
      if @liste.save
        format.html { redirect_to @liste, notice: 'Liste was successfully created.' }
        format.json { render :show, status: :created, location: @liste }
      else
        format.html { render :new }
        format.json { render json: @liste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listes/1
  # PATCH/PUT /listes/1.json
  def update
    respond_to do |format|
      if @liste.update(liste_params)
        format.html { redirect_to @liste, notice: 'Liste was successfully updated.' }
        format.json { render :show, status: :ok, location: @liste }
      else
        format.html { render :edit }
        format.json { render json: @liste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listes/1
  # DELETE /listes/1.json
  def destroy
    @liste.destroy
    respond_to do |format|
      format.html { redirect_to listes_url, notice: 'Liste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liste
      @liste = Liste.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def liste_params
      params.require(:liste).permit(:nom, :id_liste)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/listes_helper.rb
module ListesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/elements/_form.html.erb
<%= form_for(@element) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :id_liste %><br>
    <%= f.number_field :id_liste %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Editing element</h1>

<%= render 'form' %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/index.html.erb
<h1>Listing elements</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Id liste</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td><%= element.name %></td>
        <td><%= element.id_liste %></td>
        <td><%= link_to 'Show', element %></td>
        <td><%= link_to 'Edit', edit_element_path(element) %></td>
        <td><%= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Element', new_element_path %>

app/views/elements/new.html.erb
<h1>New element</h1>

<%= render 'form' %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @element.name %>
</p>

<p>
  <strong>Id liste:</strong>
  <%= @element.id_liste %>
</p>

<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> title </title>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  </head>
  <body>
    <div class="container">
      <header>
       Projet ROR, Dora LUMINEL, Romain DE LA SOUCHERE
       
        <nav class="round">
 
        </nav>
      </header>
       <ul>
      	<a href="/pages/hello">Accueil</a>.
    </ul>
      <section class="round">
        <%= yield %>
      </section>
    </div>
  </body>
</html>

app/views/listes/_form.html.erb
<%= form_for(@liste) do |f| %>
  <% if @liste.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@liste.errors.count, "error") %> prohibited this liste from being saved:</h2>

      <ul>
      <% @liste.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :id_liste %><br>
    <%= f.number_field :id_liste %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listes/edit.html.erb
<h1>Editing liste</h1>

<%= render 'form' %>

<%= link_to 'Show', @liste %> |
<%= link_to 'Back', listes_path %>

app/views/listes/index.html.erb
<h1>Listing listes</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Id liste</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listes.each do |liste| %>
      <tr>
        <td><%= liste.nom %></td>
        <td><%= liste.id_liste %></td>
        <td><%= link_to 'Show', liste %></td>
        <td><%= link_to 'Edit', edit_liste_path(liste) %></td>
        <td><%= link_to 'Destroy', liste, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Liste', new_liste_path %>

app/views/listes/new.html.erb
<h1>New liste</h1>

<%= render 'form' %>

<%= link_to 'Back', listes_path %>

app/views/listes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @liste.nom %>
</p>

<p>
  <strong>Id liste:</strong>
  <%= @liste.id_liste %>
</p>

<%= link_to 'Edit', edit_liste_path(@liste) %> |
<%= link_to 'Back', listes_path %>

app/views/pages/hello.html.erb
<h1><h1>Gestion de la base de donnée de l'application</h1></h1>

<p>
  Souhaitez vous <a href="/listes">consulter la liste des listes</a>.
</p>

<p>
  Vous pouvez aussi <a href="/elements">consulter la liste des éléments présents dans les listes</a>.
</p>